repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: parameterized
        language_version: python3.9
        args: ["--line-length", "120"]
        entry: black

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: parameterized
        args:
          [
            "--max-line-length",
            "120",
            "--ignore",
            "E203, E501, C901, W503",
            "--per-file-ignores",
            "__init__.py: F401, F403"
          ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: parameterized
        name: isort (python)
        args: [ "--profile", "black" ]
